heat_template_version: newton

description: Create Cirros instance

parameters:
  image_name:
    type: string
    default: cirros
  flavor_name:
    type: string
    default: c1.m1
  network_name:
    type: string
    default: opsta-network

resources:
  server_cirros_heat:
    type: OS::Nova::Server
    properties:
      name: cirros-heat
      flavor: { get_param: flavor_name }
      image: { get_param: image_name }
      networks:
        - network: { get_param: network_name }
      security_groups:
        - { get_resource: security_group_http_https }
        - { get_resource: security_group_ping_ssh }

  security_group_http_https:
    type: OS::Neutron::SecurityGroup
    properties:
      name: opsta-heat-http-https
      rules:
        - port_range_max: 80
          port_range_min: 80
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - port_range_max: 443
          port_range_min: 443
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0

  security_group_ping_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      name: opsta-heat-ping-ssh
      rules:
        - port_range_max: 22
          port_range_min: 22
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

outputs:
  server_ip:
    description: Cirros' server ip address
    value: { get_attr: [server_cirros_heat, first_address] }
